node {
    stage('Checkout') {
        // Tambahkan stage checkout
        checkout scm
    }

    docker.image('maven:3.9.2').inside('-v /var/jenkins_home/.m2:/root/.m2 --user root --dns 8.8.8.8 --dns 8.8.4.4') {
        env.MAVEN_OPTS = '-Dmaven.repo.local=/root/.m2/repository'

        stage('Build') {
            sh 'ls -la'
            sh 'pwd'
            sh 'mvn -B -DskipTests clean package'
        }

        stage('Test') {
            sh 'mvn test'
            junit 'target/surefire-reports/*.xml'
        }

        stage('Manual Approval') {
            input message: 'Apakah mau melanjutkan ke tahap deploy? (Click "Proceed" to continue)'
        }

        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh'
            sh 'pwd && cd target && ls -la'
            
            sh 'apt update && apt-get install -y openssh-client'
            sshagent(credentials: ['sshec2']) { 
                sh """
                    scp -r -o StrictHostKeyChecking=no target ${env.EC2_USER}@${env.EC2_HOST}:/home/ubuntu/java-maven
                """

                sh """ 
                    ssh -o StrictHostKeyChecking=no ${env.EC2_USER}@${env.EC2_HOST} 'java -jar target/my-app-1.0-SNAPSHOT.jar'

                """
            }
            // input message: 'Apakah sudah selesai menggunakan aplikasi? (Click "Proceed" to continue)'
            // sh './jenkins/scripts/kill.sh'
        }
    }
}