pipeline {
    agent {
        docker {
            image 'maven:3.9.2'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -v'
            }
        }
        stage('Test') {
            steps {
                echo 'mvn test'
            }
            
        }
        stage('Deliver') {
            steps {
                echo './jenkins/scripts/deliver.sh'
            }
        }
    }
}
